export const countries = {
  "united-states": [
      'new-york', 'los-angeles', 'chicago', 'houston', 'phoenix',
      'philadelphia', 'san-antonio', 'san-diego', 'dallas', 'san-jose',
      'austin', 'jacksonville', 'fort-worth', 'columbus', 'charlotte',
      'san-francisco', 'indianapolis', 'seattle', 'denver', 'washington',
      'boston', 'el-paso', 'nashville', 'detroit', 'oklahoma-city',
      'portland', 'las-vegas', 'memphis', 'louisville', 'baltimore',
      'milwaukee', 'albuquerque', 'tucson', 'fresno', 'sacramento',
      'mesa', 'atlanta', 'long-beach', 
      'colorado-springs', 'raleigh', 'omaha', 'oakland', 'minneapolis', 'tulsa', 'arlington',
      'tampa', 'new-orleans', 'cleveland', 'bakersfield',
      'aurora', 'anaheim', 'honolulu', 'riverside',
      'corpus-christi', 'lexington', 'henderson',
      'saint-paul', 'st-petersburg', 'cincinnati', 'pittsburgh',
      'greensboro', 'anchorage', 'plano', 'lincoln', 'orlando',
      'irvine', 'newark', 'toledo', 'durham', 'chula-vista',
      'fort-wayne', 'jersey-city', 'st-louis', 'stockton', 'santa-clarita',
      'norfolk', 'virginia-beach', 'reno', 'madison', 'salt-lake-city',
      'richmond', 'birmingham', 'miami',
      'des-moines', 'grand-rapids', 'modesto',
      'santa-ana', 'oregon-city', 'salem', 'ann-arbor', 'providence',
      'hartford', 'cambridge', 'new-haven', 'athens', 'wichita-falls',
      'jackson', 'mobile', 'augusta', 'columbia-sc', 'des-oto', 'el-monte',
      'tallahassee', 'pueblo', 'wichita', 'fayetteville', 'topeka',
      'boise', 'chattanooga', 'borders', 'eugene', 'flint', 'hampton',
      'irving', 'jefferson-city', 'kansas-city', 'lafayette', 'miami-gardens',
      'naples', 'pensacola', 'quincy', 'rochester', 'springfield',
      'utica', 'valdosta', 'yoakum', 'zanesville'
    ],
}